---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_backup_ubuntu_min
    image: ubuntu:18.04
  - name: ansible_role_backup_ubuntu_max
    image: ubuntu:20.04

provisioner:
  name: ansible
  options:
    # Docker doesn't support the init system so we skip the service registration
    # by adding --skip-tags init-system when running the ansible-playbook
    skip-tags: init-system

verifier:
  name: testinfra
